-- Baseline schema, introspected from the live database on 2026-08-03.
--
-- Why this file exists: the repo's migration history had drifted from production.
-- Two conflicting recruitment schemas were committed (supabase/migrations/005 and
-- database_migrations/create_recruitment_tables.sql) and neither matched what is
-- actually deployed, so nothing in the repo predicted the live tables. This file
-- is the reconciled truth for the tables the HR app touches.
--
-- Source: PostgREST's OpenAPI description of the public schema. That gives columns,
-- types, defaults, primary keys and foreign keys exactly as deployed. It does NOT
-- expose RLS policies, indexes, triggers, functions, check constraints or view
-- bodies -- those remain defined in migrations 001-018 and 20260726*, which stay
-- authoritative for them. Replaying this file alone gives correct tables, not a
-- correct security posture.
--
-- Every statement is IF NOT EXISTS / idempotent, so it is safe to replay against
-- the existing database.

-- Sequences backing nextval() column defaults below.
CREATE SEQUENCE IF NOT EXISTS employees_id_seq;

CREATE TABLE IF NOT EXISTS applicants (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  full_name varchar(255) NOT NULL,
  email varchar(255) NOT NULL,
  phone varchar(50),
  address text,
  date_of_birth date,
  linkedin_profile varchar(500),
  portfolio_url varchar(500),
  years_of_experience integer DEFAULT 0,
  current_company varchar(255),
  current_position varchar(255),
  education_level varchar(100),
  resume_url text,
  cover_letter text,
  skills text[],
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS hr_users (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  email varchar(255) NOT NULL,
  first_name varchar(100),
  last_name varchar(100),
  full_name varchar(255),
  phone varchar(50),
  avatar_url text,
  employee_id text,
  department varchar(100),
  position varchar(100),
  manager_id uuid,
  hire_date date,
  employment_status varchar(50) DEFAULT 'active',
  salary numeric,
  role varchar(50) DEFAULT 'employee' NOT NULL,
  is_active boolean DEFAULT true,
  email_verified boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_login timestamp with time zone,
  metadata jsonb,
  primary_email varchar(255),
  PRIMARY KEY (id)
);

-- Stores employee information
CREATE TABLE IF NOT EXISTS employees (
  id text DEFAULT nextval('public.employees_id_seq'::regclass) NOT NULL,
  name varchar(255) NOT NULL,
  position varchar(100),
  department varchar(100),
  email varchar(255) NOT NULL,
  dob date,
  address text,
  phone varchar(50),
  start_date date,
  status varchar(50) DEFAULT 'Active',
  performance numeric,
  photo text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  user_id uuid REFERENCES hr_users (id),
  pdf_document_url text,
  PRIMARY KEY (id)
);

-- Stores job openings and position details
CREATE TABLE IF NOT EXISTS job_postings (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title varchar(255) NOT NULL,
  department varchar(100) NOT NULL,
  position_type varchar(50) DEFAULT 'full-time' NOT NULL,
  description text,
  requirements text,
  responsibilities text,
  salary_range varchar(100),
  location varchar(255) DEFAULT 'Office',
  posted_by text REFERENCES employees (id),
  status varchar(50) DEFAULT 'active',
  posted_date date DEFAULT CURRENT_DATE,
  closing_date date,
  openings integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS applications (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  job_posting_id bigint REFERENCES job_postings (id),
  applicant_id uuid REFERENCES applicants (id),
  status varchar(50) DEFAULT 'under review',
  application_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  reviewed_by text REFERENCES employees (id),
  reviewed_date timestamp without time zone,
  notes text,
  rating integer,
  rejection_reason text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS employee_feedback (
  id uuid DEFAULT extensions.uuid_generate_v4() NOT NULL,
  employee_id text NOT NULL REFERENCES employees (id),
  feedback_from text REFERENCES employees (id),
  feedback_type text DEFAULT 'peer',
  rating numeric,
  feedback_text text NOT NULL,
  is_anonymous boolean DEFAULT false,
  related_review_id uuid,
  feedback_date date DEFAULT CURRENT_DATE,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);

-- Stores employee performance goals and objectives
CREATE TABLE IF NOT EXISTS performance_goals (
  id uuid DEFAULT extensions.uuid_generate_v4() NOT NULL,
  employee_id text NOT NULL REFERENCES employees (id),
  title text NOT NULL,
  description text,
  category text DEFAULT 'general',
  target_date date,
  status text DEFAULT 'pending' NOT NULL,
  progress_percentage integer DEFAULT 0,
  priority text DEFAULT 'medium',
  assigned_by text REFERENCES employees (id),
  assigned_date date DEFAULT CURRENT_DATE,
  started_date date,
  completed_date date,
  notes text,
  success_criteria text,
  related_review_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  progress integer DEFAULT 0,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS goal_milestones (
  id uuid DEFAULT extensions.uuid_generate_v4() NOT NULL,
  goal_id uuid NOT NULL REFERENCES performance_goals (id),
  title text NOT NULL,
  description text,
  due_date date,
  status text DEFAULT 'pending',
  completed_date date,
  notes text,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);

-- Stores user notifications for various system events
CREATE TABLE IF NOT EXISTS hr_notifications (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL REFERENCES hr_users (id),
  title varchar(255) NOT NULL,
  message text NOT NULL,
  type varchar(50) DEFAULT 'info' NOT NULL,
  category varchar(50) DEFAULT 'general',
  is_read boolean DEFAULT false,
  action_url varchar(500),
  action_label varchar(100),
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  read_at timestamp with time zone,
  expires_at timestamp with time zone,
  PRIMARY KEY (id)
);

-- Hand-authored translations of user-generated HR content. Machine translation runs on-device and is never persisted here.
CREATE TABLE IF NOT EXISTS hr_ugc_translations (
  entity_type text NOT NULL,
  entity_id text NOT NULL,
  field text NOT NULL,
  locale text NOT NULL,
  body text DEFAULT '' NOT NULL,
  source_text text DEFAULT '' NOT NULL,
  source_hash text DEFAULT '' NOT NULL,
  provider text DEFAULT 'manual' NOT NULL,
  updated_by uuid REFERENCES hr_users (id),
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY (entity_type, entity_id, field, locale)
);

-- Stores user-specific preferences and settings
CREATE TABLE IF NOT EXISTS hr_user_settings (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  user_id uuid NOT NULL REFERENCES hr_users (id),
  email_notifications boolean DEFAULT true,
  push_notifications boolean DEFAULT true,
  desktop_notifications boolean DEFAULT false,
  notification_frequency varchar(20) DEFAULT 'realtime',
  notify_time_tracking boolean DEFAULT true,
  notify_performance boolean DEFAULT true,
  notify_employee_updates boolean DEFAULT true,
  notify_recruitment boolean DEFAULT true,
  notify_system boolean DEFAULT true,
  theme varchar(20) DEFAULT 'system',
  language varchar(10) DEFAULT 'en',
  timezone varchar(50) DEFAULT 'UTC',
  date_format varchar(20) DEFAULT 'MM/DD/YYYY',
  time_format varchar(10) DEFAULT '12h',
  profile_visibility varchar(20) DEFAULT 'all',
  show_email boolean DEFAULT true,
  show_phone boolean DEFAULT true,
  default_dashboard_view varchar(50) DEFAULT 'overview',
  items_per_page integer DEFAULT 10,
  auto_clock_out boolean DEFAULT false,
  auto_clock_out_time time without time zone DEFAULT '18:00:00',
  weekly_report boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  notification_sound boolean DEFAULT false,
  PRIMARY KEY (id)
);

-- Tracks candidate applications for job postings
CREATE TABLE IF NOT EXISTS job_applications (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  job_posting_id bigint REFERENCES job_postings (id),
  candidate_name varchar(255) NOT NULL,
  email varchar(255) NOT NULL,
  phone varchar(50),
  resume_url text,
  cover_letter text,
  portfolio_url text,
  linkedin_url text,
  experience_years integer DEFAULT 0,
  current_company varchar(255),
  current_position varchar(255),
  expected_salary varchar(100),
  notice_period varchar(50),
  status varchar(50) DEFAULT 'applied',
  stage varchar(50) DEFAULT 'screening',
  applied_date date DEFAULT CURRENT_DATE,
  notes text,
  rating numeric,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

-- Manages interview scheduling and feedback
CREATE TABLE IF NOT EXISTS interview_schedules (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  application_id bigint NOT NULL REFERENCES job_applications (id),
  interviewer_id text REFERENCES employees (id),
  interview_type varchar(50) NOT NULL,
  scheduled_time timestamp with time zone NOT NULL,
  duration_minutes integer DEFAULT 60,
  location varchar(255),
  meeting_link text,
  notes text,
  status varchar(50) DEFAULT 'scheduled',
  feedback text,
  rating numeric,
  recommendation varchar(50),
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

-- Manages employee leave requests
CREATE TABLE IF NOT EXISTS leave_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  employee_id text NOT NULL,
  leave_type varchar(50) NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  days_count numeric NOT NULL,
  reason text,
  status varchar(50) DEFAULT 'pending',
  submitted_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  approved_by text REFERENCES employees (id),
  approved_at timestamp with time zone,
  rejection_reason text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  proof_file_url text,
  proof_file_name text,
  proof_file_type varchar(50),
  proof_file_path text,
  PRIMARY KEY (id)
);

-- Tracks overtime hours worked by employees
CREATE TABLE IF NOT EXISTS overtime_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  employee_id text NOT NULL,
  date date NOT NULL,
  hours numeric NOT NULL,
  reason text NOT NULL,
  overtime_type varchar(50) DEFAULT 'regular',
  status varchar(50) DEFAULT 'pending',
  submitted_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  approved_by text REFERENCES employees (id),
  approved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

-- Stores employee performance review data and ratings
CREATE TABLE IF NOT EXISTS performance_reviews (
  id uuid DEFAULT extensions.uuid_generate_v4() NOT NULL,
  employee_id text NOT NULL REFERENCES employees (id),
  reviewer_id text REFERENCES employees (id),
  review_period text,
  review_type text DEFAULT 'quarterly' NOT NULL,
  overall_rating numeric,
  technical_skills_rating numeric,
  communication_rating numeric,
  leadership_rating numeric,
  teamwork_rating numeric,
  problem_solving_rating numeric,
  strengths text,
  areas_for_improvement text,
  achievements text,
  comments text,
  employee_comments text,
  goals_met integer DEFAULT 0,
  goals_total integer DEFAULT 0,
  status text DEFAULT 'draft',
  review_date date DEFAULT CURRENT_DATE,
  due_date date,
  submitted_at timestamp with time zone,
  approved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS recruitment_metrics (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  job_posting_id bigint REFERENCES job_postings (id),
  total_applications integer DEFAULT 0,
  under_review integer DEFAULT 0,
  shortlisted integer DEFAULT 0,
  interviews_scheduled integer DEFAULT 0,
  offers_extended integer DEFAULT 0,
  hired integer DEFAULT 0,
  rejected integer DEFAULT 0,
  avg_time_to_hire_days numeric,
  last_updated timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

-- Employee skills inventory and ratings
CREATE TABLE IF NOT EXISTS skills_assessments (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  employee_id text NOT NULL REFERENCES employees (id),
  skill_name varchar(255) NOT NULL,
  skill_category varchar(50) DEFAULT 'technical',
  rating numeric NOT NULL,
  proficiency_level varchar(50),
  years_experience numeric,
  assessed_by text REFERENCES employees (id),
  assessment_date date DEFAULT CURRENT_DATE,
  notes text,
  certification_url text,
  last_used_date date,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

-- Records daily time clock entries for employees
CREATE TABLE IF NOT EXISTS time_entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  employee_id text NOT NULL REFERENCES employees (id),
  date date NOT NULL,
  clock_in time without time zone NOT NULL,
  clock_out time without time zone NOT NULL,
  hours numeric NOT NULL,
  hour_type varchar(50) DEFAULT 'regular' NOT NULL,
  notes text,
  proof_file_url text,
  proof_file_name text,
  proof_file_type varchar(50),
  status varchar(50) DEFAULT 'pending',
  submitted_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  approved_by text REFERENCES employees (id),
  approved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  proof_file_path text,
  PRIMARY KEY (id)
);

-- Aggregated monthly time tracking data per employee
CREATE TABLE IF NOT EXISTS time_tracking_summary (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  employee_id text NOT NULL REFERENCES employees (id),
  month integer NOT NULL,
  year integer NOT NULL,
  days_worked integer DEFAULT 0,
  leave_days numeric DEFAULT 0,
  regular_hours numeric DEFAULT 0,
  overtime_hours numeric DEFAULT 0,
  holiday_overtime_hours numeric DEFAULT 0,
  total_hours numeric DEFAULT 0,
  attendance_rate numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_emails (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  hr_user_id uuid NOT NULL REFERENCES hr_users (id),
  auth_user_id uuid NOT NULL,
  email varchar(255) NOT NULL,
  is_primary boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS visits (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  ip text,
  user_agent text,
  path text,
  referrer text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  user_id uuid,
  role text,
  is_demo boolean DEFAULT false,
  ip_region text,
  is_proxy boolean DEFAULT false,
  is_vpn boolean DEFAULT false,
  is_hosting boolean DEFAULT false,
  connection_type text DEFAULT 'unknown',
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS workload_tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  employee_id text NOT NULL REFERENCES employees (id),
  title text NOT NULL,
  description text,
  due_date date,
  priority text DEFAULT 'medium',
  status text DEFAULT 'pending',
  self_assessment text,
  quality_rating integer DEFAULT 0,
  comments text,
  created_by text REFERENCES employees (id),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  PRIMARY KEY (id)
);

-- Foreign keys whose target is created later in this file, or which point
-- back into a table already emitted.
DO $$ BEGIN
  ALTER TABLE hr_users ADD CONSTRAINT hr_users_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees (id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ---------------------------------------------------------------------------
-- Drift reconciliation.
--
-- Restates every column above as ADD COLUMN IF NOT EXISTS, so a table that an
-- earlier migration already created with a narrower column set is widened to
-- match production. This converges columns only: it cannot change a column's
-- type, drop a column production no longer has, or repair a wrong primary key.
-- Those need a hand-written migration.
-- ---------------------------------------------------------------------------
  ALTER TABLE applicants ADD COLUMN IF NOT EXISTS id uuid;
  ALTER TABLE applicants ADD COLUMN IF NOT EXISTS full_name varchar(255);
  ALTER TABLE applicants ADD COLUMN IF NOT EXISTS email varchar(255);
  ALTER TABLE applicants ADD COLUMN IF NOT EXISTS phone varchar(50);
  ALTER TABLE applicants ADD COLUMN IF NOT EXISTS address text;
  ALTER TABLE applicants ADD COLUMN IF NOT EXISTS date_of_birth date;
  ALTER TABLE applicants ADD COLUMN IF NOT EXISTS linkedin_profile varchar(500);
  ALTER TABLE applicants ADD COLUMN IF NOT EXISTS portfolio_url varchar(500);
  ALTER TABLE applicants ADD COLUMN IF NOT EXISTS years_of_experience integer;
  ALTER TABLE applicants ADD COLUMN IF NOT EXISTS current_company varchar(255);
  ALTER TABLE applicants ADD COLUMN IF NOT EXISTS current_position varchar(255);
  ALTER TABLE applicants ADD COLUMN IF NOT EXISTS education_level varchar(100);
  ALTER TABLE applicants ADD COLUMN IF NOT EXISTS resume_url text;
  ALTER TABLE applicants ADD COLUMN IF NOT EXISTS cover_letter text;
  ALTER TABLE applicants ADD COLUMN IF NOT EXISTS skills text[];
  ALTER TABLE applicants ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
  ALTER TABLE applicants ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
  ALTER TABLE hr_users ADD COLUMN IF NOT EXISTS id uuid;
  ALTER TABLE hr_users ADD COLUMN IF NOT EXISTS email varchar(255);
  ALTER TABLE hr_users ADD COLUMN IF NOT EXISTS first_name varchar(100);
  ALTER TABLE hr_users ADD COLUMN IF NOT EXISTS last_name varchar(100);
  ALTER TABLE hr_users ADD COLUMN IF NOT EXISTS full_name varchar(255);
  ALTER TABLE hr_users ADD COLUMN IF NOT EXISTS phone varchar(50);
  ALTER TABLE hr_users ADD COLUMN IF NOT EXISTS avatar_url text;
  ALTER TABLE hr_users ADD COLUMN IF NOT EXISTS employee_id text;
  ALTER TABLE hr_users ADD COLUMN IF NOT EXISTS department varchar(100);
  ALTER TABLE hr_users ADD COLUMN IF NOT EXISTS position varchar(100);
  ALTER TABLE hr_users ADD COLUMN IF NOT EXISTS manager_id uuid;
  ALTER TABLE hr_users ADD COLUMN IF NOT EXISTS hire_date date;
  ALTER TABLE hr_users ADD COLUMN IF NOT EXISTS employment_status varchar(50);
  ALTER TABLE hr_users ADD COLUMN IF NOT EXISTS salary numeric;
  ALTER TABLE hr_users ADD COLUMN IF NOT EXISTS role varchar(50);
  ALTER TABLE hr_users ADD COLUMN IF NOT EXISTS is_active boolean;
  ALTER TABLE hr_users ADD COLUMN IF NOT EXISTS email_verified boolean;
  ALTER TABLE hr_users ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
  ALTER TABLE hr_users ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
  ALTER TABLE hr_users ADD COLUMN IF NOT EXISTS last_login timestamp with time zone;
  ALTER TABLE hr_users ADD COLUMN IF NOT EXISTS metadata jsonb;
  ALTER TABLE hr_users ADD COLUMN IF NOT EXISTS primary_email varchar(255);
  ALTER TABLE employees ADD COLUMN IF NOT EXISTS id text;
  ALTER TABLE employees ADD COLUMN IF NOT EXISTS name varchar(255);
  ALTER TABLE employees ADD COLUMN IF NOT EXISTS position varchar(100);
  ALTER TABLE employees ADD COLUMN IF NOT EXISTS department varchar(100);
  ALTER TABLE employees ADD COLUMN IF NOT EXISTS email varchar(255);
  ALTER TABLE employees ADD COLUMN IF NOT EXISTS dob date;
  ALTER TABLE employees ADD COLUMN IF NOT EXISTS address text;
  ALTER TABLE employees ADD COLUMN IF NOT EXISTS phone varchar(50);
  ALTER TABLE employees ADD COLUMN IF NOT EXISTS start_date date;
  ALTER TABLE employees ADD COLUMN IF NOT EXISTS status varchar(50);
  ALTER TABLE employees ADD COLUMN IF NOT EXISTS performance numeric;
  ALTER TABLE employees ADD COLUMN IF NOT EXISTS photo text;
  ALTER TABLE employees ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
  ALTER TABLE employees ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
  ALTER TABLE employees ADD COLUMN IF NOT EXISTS user_id uuid;
  ALTER TABLE employees ADD COLUMN IF NOT EXISTS pdf_document_url text;
  ALTER TABLE job_postings ADD COLUMN IF NOT EXISTS id bigint;
  ALTER TABLE job_postings ADD COLUMN IF NOT EXISTS title varchar(255);
  ALTER TABLE job_postings ADD COLUMN IF NOT EXISTS department varchar(100);
  ALTER TABLE job_postings ADD COLUMN IF NOT EXISTS position_type varchar(50);
  ALTER TABLE job_postings ADD COLUMN IF NOT EXISTS description text;
  ALTER TABLE job_postings ADD COLUMN IF NOT EXISTS requirements text;
  ALTER TABLE job_postings ADD COLUMN IF NOT EXISTS responsibilities text;
  ALTER TABLE job_postings ADD COLUMN IF NOT EXISTS salary_range varchar(100);
  ALTER TABLE job_postings ADD COLUMN IF NOT EXISTS location varchar(255);
  ALTER TABLE job_postings ADD COLUMN IF NOT EXISTS posted_by text;
  ALTER TABLE job_postings ADD COLUMN IF NOT EXISTS status varchar(50);
  ALTER TABLE job_postings ADD COLUMN IF NOT EXISTS posted_date date;
  ALTER TABLE job_postings ADD COLUMN IF NOT EXISTS closing_date date;
  ALTER TABLE job_postings ADD COLUMN IF NOT EXISTS openings integer;
  ALTER TABLE job_postings ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
  ALTER TABLE job_postings ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
  ALTER TABLE applications ADD COLUMN IF NOT EXISTS id uuid;
  ALTER TABLE applications ADD COLUMN IF NOT EXISTS job_posting_id bigint;
  ALTER TABLE applications ADD COLUMN IF NOT EXISTS applicant_id uuid;
  ALTER TABLE applications ADD COLUMN IF NOT EXISTS status varchar(50);
  ALTER TABLE applications ADD COLUMN IF NOT EXISTS application_date timestamp without time zone;
  ALTER TABLE applications ADD COLUMN IF NOT EXISTS reviewed_by text;
  ALTER TABLE applications ADD COLUMN IF NOT EXISTS reviewed_date timestamp without time zone;
  ALTER TABLE applications ADD COLUMN IF NOT EXISTS notes text;
  ALTER TABLE applications ADD COLUMN IF NOT EXISTS rating integer;
  ALTER TABLE applications ADD COLUMN IF NOT EXISTS rejection_reason text;
  ALTER TABLE applications ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
  ALTER TABLE applications ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
  ALTER TABLE employee_feedback ADD COLUMN IF NOT EXISTS id uuid;
  ALTER TABLE employee_feedback ADD COLUMN IF NOT EXISTS employee_id text;
  ALTER TABLE employee_feedback ADD COLUMN IF NOT EXISTS feedback_from text;
  ALTER TABLE employee_feedback ADD COLUMN IF NOT EXISTS feedback_type text;
  ALTER TABLE employee_feedback ADD COLUMN IF NOT EXISTS rating numeric;
  ALTER TABLE employee_feedback ADD COLUMN IF NOT EXISTS feedback_text text;
  ALTER TABLE employee_feedback ADD COLUMN IF NOT EXISTS is_anonymous boolean;
  ALTER TABLE employee_feedback ADD COLUMN IF NOT EXISTS related_review_id uuid;
  ALTER TABLE employee_feedback ADD COLUMN IF NOT EXISTS feedback_date date;
  ALTER TABLE employee_feedback ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
  ALTER TABLE employee_feedback ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
  ALTER TABLE performance_goals ADD COLUMN IF NOT EXISTS id uuid;
  ALTER TABLE performance_goals ADD COLUMN IF NOT EXISTS employee_id text;
  ALTER TABLE performance_goals ADD COLUMN IF NOT EXISTS title text;
  ALTER TABLE performance_goals ADD COLUMN IF NOT EXISTS description text;
  ALTER TABLE performance_goals ADD COLUMN IF NOT EXISTS category text;
  ALTER TABLE performance_goals ADD COLUMN IF NOT EXISTS target_date date;
  ALTER TABLE performance_goals ADD COLUMN IF NOT EXISTS status text;
  ALTER TABLE performance_goals ADD COLUMN IF NOT EXISTS progress_percentage integer;
  ALTER TABLE performance_goals ADD COLUMN IF NOT EXISTS priority text;
  ALTER TABLE performance_goals ADD COLUMN IF NOT EXISTS assigned_by text;
  ALTER TABLE performance_goals ADD COLUMN IF NOT EXISTS assigned_date date;
  ALTER TABLE performance_goals ADD COLUMN IF NOT EXISTS started_date date;
  ALTER TABLE performance_goals ADD COLUMN IF NOT EXISTS completed_date date;
  ALTER TABLE performance_goals ADD COLUMN IF NOT EXISTS notes text;
  ALTER TABLE performance_goals ADD COLUMN IF NOT EXISTS success_criteria text;
  ALTER TABLE performance_goals ADD COLUMN IF NOT EXISTS related_review_id uuid;
  ALTER TABLE performance_goals ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
  ALTER TABLE performance_goals ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
  ALTER TABLE performance_goals ADD COLUMN IF NOT EXISTS progress integer;
  ALTER TABLE goal_milestones ADD COLUMN IF NOT EXISTS id uuid;
  ALTER TABLE goal_milestones ADD COLUMN IF NOT EXISTS goal_id uuid;
  ALTER TABLE goal_milestones ADD COLUMN IF NOT EXISTS title text;
  ALTER TABLE goal_milestones ADD COLUMN IF NOT EXISTS description text;
  ALTER TABLE goal_milestones ADD COLUMN IF NOT EXISTS due_date date;
  ALTER TABLE goal_milestones ADD COLUMN IF NOT EXISTS status text;
  ALTER TABLE goal_milestones ADD COLUMN IF NOT EXISTS completed_date date;
  ALTER TABLE goal_milestones ADD COLUMN IF NOT EXISTS notes text;
  ALTER TABLE goal_milestones ADD COLUMN IF NOT EXISTS sort_order integer;
  ALTER TABLE goal_milestones ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
  ALTER TABLE goal_milestones ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
  ALTER TABLE hr_notifications ADD COLUMN IF NOT EXISTS id uuid;
  ALTER TABLE hr_notifications ADD COLUMN IF NOT EXISTS user_id uuid;
  ALTER TABLE hr_notifications ADD COLUMN IF NOT EXISTS title varchar(255);
  ALTER TABLE hr_notifications ADD COLUMN IF NOT EXISTS message text;
  ALTER TABLE hr_notifications ADD COLUMN IF NOT EXISTS type varchar(50);
  ALTER TABLE hr_notifications ADD COLUMN IF NOT EXISTS category varchar(50);
  ALTER TABLE hr_notifications ADD COLUMN IF NOT EXISTS is_read boolean;
  ALTER TABLE hr_notifications ADD COLUMN IF NOT EXISTS action_url varchar(500);
  ALTER TABLE hr_notifications ADD COLUMN IF NOT EXISTS action_label varchar(100);
  ALTER TABLE hr_notifications ADD COLUMN IF NOT EXISTS metadata jsonb;
  ALTER TABLE hr_notifications ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
  ALTER TABLE hr_notifications ADD COLUMN IF NOT EXISTS read_at timestamp with time zone;
  ALTER TABLE hr_notifications ADD COLUMN IF NOT EXISTS expires_at timestamp with time zone;
  ALTER TABLE hr_ugc_translations ADD COLUMN IF NOT EXISTS entity_type text;
  ALTER TABLE hr_ugc_translations ADD COLUMN IF NOT EXISTS entity_id text;
  ALTER TABLE hr_ugc_translations ADD COLUMN IF NOT EXISTS field text;
  ALTER TABLE hr_ugc_translations ADD COLUMN IF NOT EXISTS locale text;
  ALTER TABLE hr_ugc_translations ADD COLUMN IF NOT EXISTS body text;
  ALTER TABLE hr_ugc_translations ADD COLUMN IF NOT EXISTS source_text text;
  ALTER TABLE hr_ugc_translations ADD COLUMN IF NOT EXISTS source_hash text;
  ALTER TABLE hr_ugc_translations ADD COLUMN IF NOT EXISTS provider text;
  ALTER TABLE hr_ugc_translations ADD COLUMN IF NOT EXISTS updated_by uuid;
  ALTER TABLE hr_ugc_translations ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
  ALTER TABLE hr_ugc_translations ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
  ALTER TABLE hr_user_settings ADD COLUMN IF NOT EXISTS id uuid;
  ALTER TABLE hr_user_settings ADD COLUMN IF NOT EXISTS user_id uuid;
  ALTER TABLE hr_user_settings ADD COLUMN IF NOT EXISTS email_notifications boolean;
  ALTER TABLE hr_user_settings ADD COLUMN IF NOT EXISTS push_notifications boolean;
  ALTER TABLE hr_user_settings ADD COLUMN IF NOT EXISTS desktop_notifications boolean;
  ALTER TABLE hr_user_settings ADD COLUMN IF NOT EXISTS notification_frequency varchar(20);
  ALTER TABLE hr_user_settings ADD COLUMN IF NOT EXISTS notify_time_tracking boolean;
  ALTER TABLE hr_user_settings ADD COLUMN IF NOT EXISTS notify_performance boolean;
  ALTER TABLE hr_user_settings ADD COLUMN IF NOT EXISTS notify_employee_updates boolean;
  ALTER TABLE hr_user_settings ADD COLUMN IF NOT EXISTS notify_recruitment boolean;
  ALTER TABLE hr_user_settings ADD COLUMN IF NOT EXISTS notify_system boolean;
  ALTER TABLE hr_user_settings ADD COLUMN IF NOT EXISTS theme varchar(20);
  ALTER TABLE hr_user_settings ADD COLUMN IF NOT EXISTS language varchar(10);
  ALTER TABLE hr_user_settings ADD COLUMN IF NOT EXISTS timezone varchar(50);
  ALTER TABLE hr_user_settings ADD COLUMN IF NOT EXISTS date_format varchar(20);
  ALTER TABLE hr_user_settings ADD COLUMN IF NOT EXISTS time_format varchar(10);
  ALTER TABLE hr_user_settings ADD COLUMN IF NOT EXISTS profile_visibility varchar(20);
  ALTER TABLE hr_user_settings ADD COLUMN IF NOT EXISTS show_email boolean;
  ALTER TABLE hr_user_settings ADD COLUMN IF NOT EXISTS show_phone boolean;
  ALTER TABLE hr_user_settings ADD COLUMN IF NOT EXISTS default_dashboard_view varchar(50);
  ALTER TABLE hr_user_settings ADD COLUMN IF NOT EXISTS items_per_page integer;
  ALTER TABLE hr_user_settings ADD COLUMN IF NOT EXISTS auto_clock_out boolean;
  ALTER TABLE hr_user_settings ADD COLUMN IF NOT EXISTS auto_clock_out_time time without time zone;
  ALTER TABLE hr_user_settings ADD COLUMN IF NOT EXISTS weekly_report boolean;
  ALTER TABLE hr_user_settings ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
  ALTER TABLE hr_user_settings ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
  ALTER TABLE hr_user_settings ADD COLUMN IF NOT EXISTS notification_sound boolean;
  ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS id bigint;
  ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS job_posting_id bigint;
  ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS candidate_name varchar(255);
  ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS email varchar(255);
  ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS phone varchar(50);
  ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS resume_url text;
  ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS cover_letter text;
  ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS portfolio_url text;
  ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS linkedin_url text;
  ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS experience_years integer;
  ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS current_company varchar(255);
  ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS current_position varchar(255);
  ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS expected_salary varchar(100);
  ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS notice_period varchar(50);
  ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS status varchar(50);
  ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS stage varchar(50);
  ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS applied_date date;
  ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS notes text;
  ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS rating numeric;
  ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
  ALTER TABLE job_applications ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
  ALTER TABLE interview_schedules ADD COLUMN IF NOT EXISTS id bigint;
  ALTER TABLE interview_schedules ADD COLUMN IF NOT EXISTS application_id bigint;
  ALTER TABLE interview_schedules ADD COLUMN IF NOT EXISTS interviewer_id text;
  ALTER TABLE interview_schedules ADD COLUMN IF NOT EXISTS interview_type varchar(50);
  ALTER TABLE interview_schedules ADD COLUMN IF NOT EXISTS scheduled_time timestamp with time zone;
  ALTER TABLE interview_schedules ADD COLUMN IF NOT EXISTS duration_minutes integer;
  ALTER TABLE interview_schedules ADD COLUMN IF NOT EXISTS location varchar(255);
  ALTER TABLE interview_schedules ADD COLUMN IF NOT EXISTS meeting_link text;
  ALTER TABLE interview_schedules ADD COLUMN IF NOT EXISTS notes text;
  ALTER TABLE interview_schedules ADD COLUMN IF NOT EXISTS status varchar(50);
  ALTER TABLE interview_schedules ADD COLUMN IF NOT EXISTS feedback text;
  ALTER TABLE interview_schedules ADD COLUMN IF NOT EXISTS rating numeric;
  ALTER TABLE interview_schedules ADD COLUMN IF NOT EXISTS recommendation varchar(50);
  ALTER TABLE interview_schedules ADD COLUMN IF NOT EXISTS completed_at timestamp with time zone;
  ALTER TABLE interview_schedules ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
  ALTER TABLE interview_schedules ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
  ALTER TABLE leave_requests ADD COLUMN IF NOT EXISTS id bigint;
  ALTER TABLE leave_requests ADD COLUMN IF NOT EXISTS employee_id text;
  ALTER TABLE leave_requests ADD COLUMN IF NOT EXISTS leave_type varchar(50);
  ALTER TABLE leave_requests ADD COLUMN IF NOT EXISTS start_date date;
  ALTER TABLE leave_requests ADD COLUMN IF NOT EXISTS end_date date;
  ALTER TABLE leave_requests ADD COLUMN IF NOT EXISTS days_count numeric;
  ALTER TABLE leave_requests ADD COLUMN IF NOT EXISTS reason text;
  ALTER TABLE leave_requests ADD COLUMN IF NOT EXISTS status varchar(50);
  ALTER TABLE leave_requests ADD COLUMN IF NOT EXISTS submitted_at timestamp with time zone;
  ALTER TABLE leave_requests ADD COLUMN IF NOT EXISTS approved_by text;
  ALTER TABLE leave_requests ADD COLUMN IF NOT EXISTS approved_at timestamp with time zone;
  ALTER TABLE leave_requests ADD COLUMN IF NOT EXISTS rejection_reason text;
  ALTER TABLE leave_requests ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
  ALTER TABLE leave_requests ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
  ALTER TABLE leave_requests ADD COLUMN IF NOT EXISTS proof_file_url text;
  ALTER TABLE leave_requests ADD COLUMN IF NOT EXISTS proof_file_name text;
  ALTER TABLE leave_requests ADD COLUMN IF NOT EXISTS proof_file_type varchar(50);
  ALTER TABLE leave_requests ADD COLUMN IF NOT EXISTS proof_file_path text;
  ALTER TABLE overtime_logs ADD COLUMN IF NOT EXISTS id bigint;
  ALTER TABLE overtime_logs ADD COLUMN IF NOT EXISTS employee_id text;
  ALTER TABLE overtime_logs ADD COLUMN IF NOT EXISTS date date;
  ALTER TABLE overtime_logs ADD COLUMN IF NOT EXISTS hours numeric;
  ALTER TABLE overtime_logs ADD COLUMN IF NOT EXISTS reason text;
  ALTER TABLE overtime_logs ADD COLUMN IF NOT EXISTS overtime_type varchar(50);
  ALTER TABLE overtime_logs ADD COLUMN IF NOT EXISTS status varchar(50);
  ALTER TABLE overtime_logs ADD COLUMN IF NOT EXISTS submitted_at timestamp with time zone;
  ALTER TABLE overtime_logs ADD COLUMN IF NOT EXISTS approved_by text;
  ALTER TABLE overtime_logs ADD COLUMN IF NOT EXISTS approved_at timestamp with time zone;
  ALTER TABLE overtime_logs ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
  ALTER TABLE overtime_logs ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
  ALTER TABLE performance_reviews ADD COLUMN IF NOT EXISTS id uuid;
  ALTER TABLE performance_reviews ADD COLUMN IF NOT EXISTS employee_id text;
  ALTER TABLE performance_reviews ADD COLUMN IF NOT EXISTS reviewer_id text;
  ALTER TABLE performance_reviews ADD COLUMN IF NOT EXISTS review_period text;
  ALTER TABLE performance_reviews ADD COLUMN IF NOT EXISTS review_type text;
  ALTER TABLE performance_reviews ADD COLUMN IF NOT EXISTS overall_rating numeric;
  ALTER TABLE performance_reviews ADD COLUMN IF NOT EXISTS technical_skills_rating numeric;
  ALTER TABLE performance_reviews ADD COLUMN IF NOT EXISTS communication_rating numeric;
  ALTER TABLE performance_reviews ADD COLUMN IF NOT EXISTS leadership_rating numeric;
  ALTER TABLE performance_reviews ADD COLUMN IF NOT EXISTS teamwork_rating numeric;
  ALTER TABLE performance_reviews ADD COLUMN IF NOT EXISTS problem_solving_rating numeric;
  ALTER TABLE performance_reviews ADD COLUMN IF NOT EXISTS strengths text;
  ALTER TABLE performance_reviews ADD COLUMN IF NOT EXISTS areas_for_improvement text;
  ALTER TABLE performance_reviews ADD COLUMN IF NOT EXISTS achievements text;
  ALTER TABLE performance_reviews ADD COLUMN IF NOT EXISTS comments text;
  ALTER TABLE performance_reviews ADD COLUMN IF NOT EXISTS employee_comments text;
  ALTER TABLE performance_reviews ADD COLUMN IF NOT EXISTS goals_met integer;
  ALTER TABLE performance_reviews ADD COLUMN IF NOT EXISTS goals_total integer;
  ALTER TABLE performance_reviews ADD COLUMN IF NOT EXISTS status text;
  ALTER TABLE performance_reviews ADD COLUMN IF NOT EXISTS review_date date;
  ALTER TABLE performance_reviews ADD COLUMN IF NOT EXISTS due_date date;
  ALTER TABLE performance_reviews ADD COLUMN IF NOT EXISTS submitted_at timestamp with time zone;
  ALTER TABLE performance_reviews ADD COLUMN IF NOT EXISTS approved_at timestamp with time zone;
  ALTER TABLE performance_reviews ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
  ALTER TABLE performance_reviews ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
  ALTER TABLE recruitment_metrics ADD COLUMN IF NOT EXISTS id uuid;
  ALTER TABLE recruitment_metrics ADD COLUMN IF NOT EXISTS job_posting_id bigint;
  ALTER TABLE recruitment_metrics ADD COLUMN IF NOT EXISTS total_applications integer;
  ALTER TABLE recruitment_metrics ADD COLUMN IF NOT EXISTS under_review integer;
  ALTER TABLE recruitment_metrics ADD COLUMN IF NOT EXISTS shortlisted integer;
  ALTER TABLE recruitment_metrics ADD COLUMN IF NOT EXISTS interviews_scheduled integer;
  ALTER TABLE recruitment_metrics ADD COLUMN IF NOT EXISTS offers_extended integer;
  ALTER TABLE recruitment_metrics ADD COLUMN IF NOT EXISTS hired integer;
  ALTER TABLE recruitment_metrics ADD COLUMN IF NOT EXISTS rejected integer;
  ALTER TABLE recruitment_metrics ADD COLUMN IF NOT EXISTS avg_time_to_hire_days numeric;
  ALTER TABLE recruitment_metrics ADD COLUMN IF NOT EXISTS last_updated timestamp without time zone;
  ALTER TABLE skills_assessments ADD COLUMN IF NOT EXISTS id bigint;
  ALTER TABLE skills_assessments ADD COLUMN IF NOT EXISTS employee_id text;
  ALTER TABLE skills_assessments ADD COLUMN IF NOT EXISTS skill_name varchar(255);
  ALTER TABLE skills_assessments ADD COLUMN IF NOT EXISTS skill_category varchar(50);
  ALTER TABLE skills_assessments ADD COLUMN IF NOT EXISTS rating numeric;
  ALTER TABLE skills_assessments ADD COLUMN IF NOT EXISTS proficiency_level varchar(50);
  ALTER TABLE skills_assessments ADD COLUMN IF NOT EXISTS years_experience numeric;
  ALTER TABLE skills_assessments ADD COLUMN IF NOT EXISTS assessed_by text;
  ALTER TABLE skills_assessments ADD COLUMN IF NOT EXISTS assessment_date date;
  ALTER TABLE skills_assessments ADD COLUMN IF NOT EXISTS notes text;
  ALTER TABLE skills_assessments ADD COLUMN IF NOT EXISTS certification_url text;
  ALTER TABLE skills_assessments ADD COLUMN IF NOT EXISTS last_used_date date;
  ALTER TABLE skills_assessments ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
  ALTER TABLE skills_assessments ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
  ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS id bigint;
  ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS employee_id text;
  ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS date date;
  ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS clock_in time without time zone;
  ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS clock_out time without time zone;
  ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS hours numeric;
  ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS hour_type varchar(50);
  ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS notes text;
  ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS proof_file_url text;
  ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS proof_file_name text;
  ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS proof_file_type varchar(50);
  ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS status varchar(50);
  ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS submitted_at timestamp with time zone;
  ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS approved_by text;
  ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS approved_at timestamp with time zone;
  ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
  ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
  ALTER TABLE time_entries ADD COLUMN IF NOT EXISTS proof_file_path text;
  ALTER TABLE time_tracking_summary ADD COLUMN IF NOT EXISTS id bigint;
  ALTER TABLE time_tracking_summary ADD COLUMN IF NOT EXISTS employee_id text;
  ALTER TABLE time_tracking_summary ADD COLUMN IF NOT EXISTS month integer;
  ALTER TABLE time_tracking_summary ADD COLUMN IF NOT EXISTS year integer;
  ALTER TABLE time_tracking_summary ADD COLUMN IF NOT EXISTS days_worked integer;
  ALTER TABLE time_tracking_summary ADD COLUMN IF NOT EXISTS leave_days numeric;
  ALTER TABLE time_tracking_summary ADD COLUMN IF NOT EXISTS regular_hours numeric;
  ALTER TABLE time_tracking_summary ADD COLUMN IF NOT EXISTS overtime_hours numeric;
  ALTER TABLE time_tracking_summary ADD COLUMN IF NOT EXISTS holiday_overtime_hours numeric;
  ALTER TABLE time_tracking_summary ADD COLUMN IF NOT EXISTS total_hours numeric;
  ALTER TABLE time_tracking_summary ADD COLUMN IF NOT EXISTS attendance_rate numeric;
  ALTER TABLE time_tracking_summary ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
  ALTER TABLE time_tracking_summary ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
  ALTER TABLE user_emails ADD COLUMN IF NOT EXISTS id integer;
  ALTER TABLE user_emails ADD COLUMN IF NOT EXISTS hr_user_id uuid;
  ALTER TABLE user_emails ADD COLUMN IF NOT EXISTS auth_user_id uuid;
  ALTER TABLE user_emails ADD COLUMN IF NOT EXISTS email varchar(255);
  ALTER TABLE user_emails ADD COLUMN IF NOT EXISTS is_primary boolean;
  ALTER TABLE user_emails ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
  ALTER TABLE visits ADD COLUMN IF NOT EXISTS id uuid;
  ALTER TABLE visits ADD COLUMN IF NOT EXISTS ip text;
  ALTER TABLE visits ADD COLUMN IF NOT EXISTS user_agent text;
  ALTER TABLE visits ADD COLUMN IF NOT EXISTS path text;
  ALTER TABLE visits ADD COLUMN IF NOT EXISTS referrer text;
  ALTER TABLE visits ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
  ALTER TABLE visits ADD COLUMN IF NOT EXISTS user_id uuid;
  ALTER TABLE visits ADD COLUMN IF NOT EXISTS role text;
  ALTER TABLE visits ADD COLUMN IF NOT EXISTS is_demo boolean;
  ALTER TABLE visits ADD COLUMN IF NOT EXISTS ip_region text;
  ALTER TABLE visits ADD COLUMN IF NOT EXISTS is_proxy boolean;
  ALTER TABLE visits ADD COLUMN IF NOT EXISTS is_vpn boolean;
  ALTER TABLE visits ADD COLUMN IF NOT EXISTS is_hosting boolean;
  ALTER TABLE visits ADD COLUMN IF NOT EXISTS connection_type text;
  ALTER TABLE workload_tasks ADD COLUMN IF NOT EXISTS id bigint;
  ALTER TABLE workload_tasks ADD COLUMN IF NOT EXISTS employee_id text;
  ALTER TABLE workload_tasks ADD COLUMN IF NOT EXISTS title text;
  ALTER TABLE workload_tasks ADD COLUMN IF NOT EXISTS description text;
  ALTER TABLE workload_tasks ADD COLUMN IF NOT EXISTS due_date date;
  ALTER TABLE workload_tasks ADD COLUMN IF NOT EXISTS priority text;
  ALTER TABLE workload_tasks ADD COLUMN IF NOT EXISTS status text;
  ALTER TABLE workload_tasks ADD COLUMN IF NOT EXISTS self_assessment text;
  ALTER TABLE workload_tasks ADD COLUMN IF NOT EXISTS quality_rating integer;
  ALTER TABLE workload_tasks ADD COLUMN IF NOT EXISTS comments text;
  ALTER TABLE workload_tasks ADD COLUMN IF NOT EXISTS created_by text;
  ALTER TABLE workload_tasks ADD COLUMN IF NOT EXISTS created_at timestamp with time zone;
  ALTER TABLE workload_tasks ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone;
