// Export all components from a single file for easier imports
export { default as Dashboard } from './dashboard.jsx';
export { default as Employee } from './employee.jsx';
export { default as EmployeeCard } from './employeeCard.jsx';
export { default as EmployeeModal } from './employeeModal.jsx';
export { default as Header } from './header.jsx';
export { default as LanguageSelector } from './LanguageSelector.jsx';
export { default as Login } from './login.jsx';
export { default as ResetPassword } from './ResetPassword.jsx';
export { default as TaskListing } from './taskListing.jsx';
export { default as ProductionHelpCenter } from './ProductionHelpCenter';
export { default as PlaceHolder } from './placeHolder.jsx';
export { default as Recruitment } from './recruitment.jsx';
export { default as Reports } from './reports.jsx';
export { default as SearchAndFilter } from './search.jsx';
export { default as Sidebar } from './sidebar.jsx';
export { default as StatsCard } from './statsCard.jsx';
export { default as ThemeToggle } from './themeToggle.jsx';
export { default as TimeTracking } from './timeTracking.jsx';
export { default as TimeClockEntry } from './timeClockEntry.jsx';
export { default as Search } from './search.jsx';
export { default as Notifications } from './notifications.jsx';
export { default as Settings } from './settings.jsx';
export { default as AddNewEmployee } from './addNewEmployee.jsx';
export { default as MetricDetailModal } from './metricDetailModal.jsx';
export { default as DeleteEmployeeManager } from './deleteEmployeeManager.jsx';
export { default as ControlPanel } from './controlPanel.jsx';
export { default as AdvancedHelpCenter } from './AdvancedHelpCenter.jsx';
export { default as VideoPlayer } from './VideoPlayer.jsx';
export { default as UserEmployeeCard } from './userEmployeeCard.jsx';
export { default as UserManagement } from './userManagement.jsx';
export { default as TaskReview } from './taskReview.jsx';
export { default as PersonalGoals } from './personalGoals.jsx';
export { default as FlubberIconTest } from './FlubberIconTest.jsx';
export { default as EmployeeDetailModal } from './employeeDetailModal.jsx';
export { AnimatedClockIcon } from './timeClockEntry.jsx';
export { AnimatedAlarmClockIcon } from './timeClockEntry.jsx';
export { AnimatedCoffeeIcon } from './timeTracking.jsx';
export { MiniFlubberMorphingLeaveStatus } from './timeTracking.jsx';
export { MiniFlubberAutoMorphEmployees } from './taskReview.jsx';
export { MiniFlubberAutoMorphInProgress } from './taskReview.jsx';
export { MiniFlubberAutoMorphTotalTasks } from './taskReview.jsx';
export { MiniFlubberAutoMorphCompletionRate } from './taskReview.jsx';
export { MiniFlubberAutoMorphQuality } from './taskReview.jsx';
export { MiniFlubberAutoMorphCompletedWork } from './taskReview.jsx';
export { MiniFlubberAutoMorphOverdueTasks } from './taskReview.jsx';
export { MiniFlubberAutoMorphVacation } from './dashboard.jsx';
export { MiniFlubberAutoMorphOverTime } from './dashboard.jsx';
export { MiniFlubberAutoMorphOfficeWork } from './dashboard.jsx';
export { MiniFlubberAutoMorphPerformance } from './dashboard.jsx';
export { MiniFlubberAutoMorphDelete } from './notifications.jsx';
export { MiniFlubberAutoMorphChangeRole } from './controlPanel.jsx';
// ...other exports
