/**
 * Translate the fixed notification copy generated by this application.
 *
 * Unknown text is returned unchanged because notification rows can also carry
 * employee-authored or externally supplied content. Those strings are data,
 * not UI chrome, and must not be mistaken for catalog keys.
 */

const SYSTEM_TITLE_KEYS = {
  'Pending Approvals': 'notifications.pendingApprovals',
  'Time Entry Approved': 'notifications.timeEntryApproved',
  'Time Entry Rejected': 'notifications.timeEntryRejected',
  'New Employee Added': 'notifications.newEmployeeAdded',
  'Performance Review': 'notifications.performanceReview',
  'System Update': 'notifications.systemUpdate',
};

const SYSTEM_ACTION_KEYS = {
  'Review Now': 'notifications.reviewNow',
  'View Details': 'notifications.viewDetails',
};

export const localizeSystemNotificationTitle = (title, t) => {
  const source = title || '';
  const key = SYSTEM_TITLE_KEYS[source];
  return key && typeof t === 'function' ? t(key, source) : source;
};

export const localizeSystemNotificationMessage = (message, t) => {
  const source = message || '';
  const timeEntriesMatch = source.match(
    /^You have (\d+) time (?:entry|entries) awaiting approval\.?$/
  );

  if (!timeEntriesMatch || typeof t !== 'function') return source;

  return t('notifications.timeEntriesAwaiting', source)
    .replace('{0}', timeEntriesMatch[1]);
};

export const localizeSystemNotificationActionLabel = (label, t) => {
  const source = label || '';
  const key = SYSTEM_ACTION_KEYS[source];
  return key && typeof t === 'function' ? t(key, source) : source;
};
